### ISSUE TITLE
Ability to remove Dublin Core metadata

### ISSUE THREAD

**Issue by coryschires** [redfield/hypdf#1]
I've recently started using `HyPDF.editmeta` to clear our PDFs of any metadata which might reveal the author's identity. It's working pretty well but we're running into one issue: `editmeta` does not remove [Dublin Core metadata](https://en.wikipedia.org/wiki/Dublin_Core).

Dublin Core metatags are commonly used to describe documents in publishing – especially academic publishing. You can see these tags when viewing to IO string (notice `dc:creator` tag below) which HyPDF returns after running `editmeta`:

```
<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.6-c015 81.157285, 2014/12/12-00:43:15        ">
   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description rdf:about=""
            xmlns:xmp="http://ns.adobe.com/xap/1.0/"
            xmlns:dc="http://purl.org/dc/elements/1.1/"
            xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
            xmlns:pdf="http://ns.adobe.com/pdf/1.3/">
         <xmp:ModifyDate>2015-07-28T13:26:50+01:00</xmp:ModifyDate>
         <xmp:CreateDate>2015-07-28T13:25:16+01:00</xmp:CreateDate>
         <xmp:MetadataDate>2015-07-28T13:26:50+01:00</xmp:MetadataDate>
         <xmp:CreatorTool>Adobe Acrobat Pro DC 15.7.20033</xmp:CreatorTool>
         <dc:format>application/pdf</dc:format>
         <dc:creator>
            <rdf:Seq>
               <rdf:li>julia.bastek</rdf:li>
            </rdf:Seq>
         </dc:creator>
         <xmpMM:DocumentID>uuid:e0f932a1-c20f-43f9-b63e-36a94c73d92c</xmpMM:DocumentID>
         <xmpMM:InstanceID>uuid:314e1917-c366-4694-9b88-7da7898734c5</xmpMM:InstanceID>
         <pdf:Producer>Adobe Acrobat Pro DC 15.7.20033</pdf:Producer>
      </rdf:Description>
   </rdf:RDF>
</x:xmpmeta>
```

Unfortunately, these Dublin Core values are visible by opening the PDF and clicking _File > Properties..._. For example I see:

![screen shot 2016-03-24 at 1 01 56 pm](https://cloud.githubusercontent.com/assets/104563/14027173/548bc012-f1c4-11e5-943b-8201ece4b444.png)

As far as I can tell, `editmeta` does in fact clear the standard `Author` metadata field. But the value of `dc:creator` seems to be overriding `Author` and displaying in the UI. That's no good since, as I said, our goal is to remove any information which might identify the author.

Is there anyway for `editmeta` to remove these tags?

**Comment by redfield** [comment]
@coryschires thanks for such detailed description. We've improved the "editmeta" method and now it can access the Dublin Core-meta information. Also we've added the short-key "all" to update all tags at once. So to delete the whole meta-information from document you need to use just two options: 

`HyPDF.editmeta(YOUR_PDF, "all" => "", "xmp-dc:all" => "")`

See our documentation for more information: https://devcenter.heroku.com/articles/hypdf#editmeta

Let me know if you'll have any questions.
